app:
  name: sticker-collection
  port: 8081

db:
  dialect: postgres
  host: host.docker.internal
  port: 5432
  db_name: sticker-collection # database name
  username: admin # database user
  password: admin # database password

jwt:
  key: uwoww_sangad
  expired_minute: 30

logger:
  enable: false