version: "3"

services:
  backend:
    image: ghcr.io/rilgilang/kosan-api:latest  # Use the GHCR image
    container_name: backend
    hostname: backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`rilgilang.duckdns.org`)"
      - "traefik.http.routers.myapp.entrypoints=websecure"
      - "traefik.http.routers.myapp.tls.certresolver=letsencrypt"
    networks:
      - web
      - database
    volumes:
      - ./:/go/src/github.com/rilgilang/kosan-api/
    ports:
      - 8081:8081
    restart: always  # Ensures it restarts if it crashes

networks:
  web:
    external: true
  database:
    external: true
