version: "3"

services:
  kosan-api:
    image: ghcr.io/rilgilang/kosan-api/kosan-api:latest  # Use the GHCR image
    container_name: kosan-api
    hostname: kosan-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kosan-api.rule=Host(`rilgilang.duckdns.org`) && PathPrefix(`/kosan`)"
      - "traefik.http.routers.kosan-api.entrypoints=websecure"
      - "traefik.http.routers.kosan-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.kosan-api.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.kosan-strip.stripprefix.prefixes=/kosan"
      - "traefik.http.routers.kosan-api.middlewares=kosan-strip"
    networks:
      - web
      - database
    volumes:
      - ./:/go/src/github.com/rilgilang/kosan-api/
    ports:
      - 8081:8081
    restart: always  # Ensures it restarts if it crashes
    env_file:
      - .env

networks:
  web:
    external: true
  database:
    external: true
