name: Deploy Go App with Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: "kosan-api"
  VPS_APP_PATH: "~/apps/kosan-api"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Save Docker Image
        run: |
          docker save -o $IMAGE_NAME.tar $IMAGE_NAME:latest

      - name: Transfer Docker Image to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

          scp $IMAGE_NAME.tar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:$VPS_APP_PATH/

      - name: Deploy on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/gilang/kosan-api

            # Load new Docker image
            docker load -i kosan-api.tar

            # Stop and remove the old container
            docker stop kosan-api || true
            docker rm kosan-api || true

            # Run the new container
            docker run -d --name kosan-api -p 8080:8080 kosan-api:latest

            # Remove old Docker images to free space
            docker image prune -f
          EOF
