name: Deploy to VPS via GHCR

on:
  push:
    branches:
      - master  # Runs when pushing to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and Push Docker Image to GHCR
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/kosan-api
          docker build -t $IMAGE_NAME:latest -f ./deployment/Dockerfile .
          docker push $IMAGE_NAME:latest

      # Deploy on VPS using SSH
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest docker-compose.yaml..."
            cd /path/to/your/project  # Update this path
            git pull origin master

            echo "Stopping existing container..."
            docker compose down

            echo "Pulling latest image..."
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GH_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/kosan-api:latest

            echo "Starting new container..."
            docker compose up -d
